CREATE TABLE CLIENTES
(
     CODIGO INTEGER NOT NULL,
     CPF VARCHAR(11) NOT NULL,
     NOME VARCHAR(50) NOT NULL,
     CONSTRAINT PK_CLIENTES PRIMARY KEY(CODIGO)
 );

 CREATE SEQUENCE GEN_CODIGOCLIENTE;
