CREATE TABLE PEDIDOS_VENDA
(
     CODIGO INTEGER NOT NULL,
     PRODUTO_ID INTEGER NOT NULL,
     CLIENTE_ID INTEGER NOT NULL,
     REGISTRO_ID VARCHAR(20),
     DT_PEDIDO DATE NOT NULL,
     QTDE_ITEM NUMERIC(18,4),
     VALOR_TOTAL NUMERIC(18,2),
     STATUS CHAR(1) DEFAULT 'A' NOT NULL, --A = Aberto / C = Cooncluido / R - Aguardando Receita
     CONSTRAINT PK_PEDIDOS_VENDA PRIMARY KEY(CODIGO),
     CONSTRAINT FK_PEDIDOSVENDAXPRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS (CODIGO) ON UPDATE CASCADE,
     CONSTRAINT FK_PEDIDOSVENDAXCLIENTES FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (CODIGO) ON UPDATE CASCADE,
     CONSTRAINT FK_PEDIDOSVENDAXTECAGRICOLA FOREIGN KEY (REGISTRO_ID) REFERENCES TECNICO_AGRICOLA (NUMERO_REGISTRO) ON UPDATE CASCADE
 );

  CREATE SEQUENCE GEN_PEDIDOSVENDA;