CREATE TABLE PRODUTOS
(
     CODIGO INTEGER NOT NULL,
     DESCRICAO VARCHAR(200) NOT NULL,
     VALOR NUMERIC(18,2),
     EXIGE_CONTROLE_ESPECIAL INTEGER DEFAULT 0,
     CONSTRAINT PK_PRODUTOS PRIMARY KEY(CODIGO)
 );

  CREATE SEQUENCE GEN_CODIGOPRODUTO;
